
import { alpha } from "@mui/material";
import {theme} from "../utils/theme";


export const StatusColorMap: { [key: string]: string } = {
  PHONE_CALL: "#FFF9F2",
  OAT_DELIVERY: "#FBF4FF",
  CONSULT_OR_RECORDS: "#FFFDF1",
  FOLLOW_UP_OAT: "#F5FEFF",
  NO_SHOW_HST_EDUCATION: theme.palette.error.light,
  COMPLETE_HST_EDUCATION: "#049B22",
  ACTIVE: theme.palette.success.light,
  INACTIVE: theme.palette.error.light,
  ENABLE: theme.palette.success.main,
  ENABLED: theme.palette.success.main,
  DISABLE: theme.palette.error.light,
  DISABLED: theme.palette.error.light,
  PENDING: theme.palette.warning.light,
  PROCESSING: "#0288D1", // info.light/cyan - Light Blue for ongoing activity
  APPROVED: theme.palette.success.main,
  REJECTED: theme.palette.error.light,
  CANCELLED: theme.palette.error.light,
  SUCCESSFUL: "#2E7D32", // success.main - Green for completed successfully
  FAILED: "#D32F2F", // error.main - Red for operation failed
  CANCEL: theme.palette.error.light,
  COMPLETED: theme.palette.success.main,
  DISCARDED: alpha(theme.palette.primary.main, 0.5),
  RESCHEDULE: "#903EBC",
  NO_SHOW: "#D22B2B",
  NOSHOW: "#03A9C2",
  SCHEDULED: "#105FCE",
  CHECKED_IN: "#B50ED2",
  SEEN: "#049B22",
  IN_SESSION: "#4C3EEA",
  SIGN_OFF: "#E1C332",
  PENALTIES: "#D2730D",
  INITIAL_TELEHEALTH: "#F2F7FF",
  FOLLOW_UP_OAT_ANNUAL: "#F2F7FF",
  EVAL_OR_SCREENING: "#F4FFF2",
  FOLLOWUP_TELEHEALTH_REGULAR: "#FDF3FF",
  HST: "#F3F2FF",
  FOLLOWUP_TELEHEALTH_DME: "#EAFFFE",
  IN_EXAM: theme.palette.warning.light,
  CHECK_IN: theme.palette.success.main,
  CONFIRMED: theme.palette.success.main,
  PAY_NOW: theme.palette.success.main,
  CONFIRMATION_PENDING: theme.palette.warning.light,
  INTAKE_PENDING: theme.palette.warning.light,
  SCREENERS_PENDING: theme.palette.warning.light,
  PAYMENT_PENDING: theme.palette.warning.light,
  ABLE_TO_CHECK_IN: theme.palette.success.main,
  FEES_NOT_SET: theme.palette.warning.light,
  NO_SHOW_FROM_PROVIDER: alpha(theme.palette.common.black, 0.5),
  SIGN_OFF_PENDING: theme.palette.warning.light,
  HIGH: theme.palette.error.light,
  MEDIUM: theme.palette.info.main,
  ACTIVE_COVERAGE: theme.palette.success.main,
  LOW: theme.palette.warning.light,
  YES: theme.palette.primary.light,
  NO: theme.palette.primary.light,
  INITIATED: theme.palette.primary.light,
  SIGN_OFF_REQUIRED: theme.palette.error.dark,
  READY_FOR_BILL: theme.palette.success.main,
  READY_FOR_PAYMENT: theme.palette.primary.light,
  READY_FOR_CLAIM: theme.palette.success.main,
  READY_FOR_SELF_PAY: theme.palette.warning.light,
  CLAIM_IN_PROGRESS: theme.palette.warning.light,
  HOLD: theme.palette.primary.light,
  SETTLED: theme.palette.success.main,
  SIGNED_OFF: theme.palette.success.main,
  IN_PROGRESS: theme.palette.warning.light,
  IN_USE: "#0D58A4",
  READY: "#049B22",
  LOST: "#B1000F",
  BROKEN: "#943C00",
  NEW_ORDER: "#004AB1",
  ARCHIVED: theme.palette.grey[500],
  None: theme.palette.success.light,
  FIRST_CALL: "#6A1E55",
  SECOND_CALL: "#049B22",
  SCANS_SENT_TO_LAB: "#A27B5C",
  APPLIANCE_RECEIVED: "#2484AD",
  DELAYED_FOR_FINANCIAL: "#D72323",
  DELAYED_FOR_DENTAL_WORK: "#FFD700",
  DELAYED_FOR_PAP_TRIAL: "#FF204E",
  HIGH_DEDUCTIBLE: "#AD49E1",
  NO_SHOW_NEED_RESCHEDULE: "#FF6500",
  REFERRED_FOR_SLEEP_TEST: "#EC625F",
  PT_REQ_ORDER_FROM_MD: "#943C00",
  UNABLE_TO_CONTACT: "#616F39",
  PRIMARY: "#943C00",
  SECONDARY: theme.palette.warning.main,
  HST_EQUIPMENT: "#F3F2FF",
  NEW_PATIENT: "#2484AD",
  RESCHEDULED: "#FF6500",
  DRAFT_NOTE: "#FF4F00",
  CLOSED: theme.palette.error.light,
  SIGNED: theme.palette.success.light,
  ON_HOLD: "#AD49E1",
  CREATED: "#105FCE",
  READY_TO_REVIEW: "#616F39",
  READY_TO_BILL: "#D72323",
  BILLED: "#FFD700",
  RESUMED: "#AD49E1",
  VOB_PENDING: "#105FCE",
  MISSING_INFO: "#FF6500",
  NO_ACTIVE_INSURANCE: "#EC625F",
  MISSING_DOCS: "#616F39",
  AUTH_PENDING: "#943C00",
  FINANCIAL_REVIEW_PENDING: "#D72323",
  REVIEWED: "#FFD700",
  AUTH_REQUIRED: "#FF204E",
  READY_TO_SCHEDULE: "#AD49E1",
  THIRD_CALL: "#6A1E55",
  MALE: theme.palette.primary.light,
  FEMALE: theme.palette.primary.light,
  "1st Call": "#6A1E55",
  RETIRED: "#AD49E1",
  POSSIBLE_ISSUE: "#FF6500",
  REPLACED: "#FFD700",
};