import type { ClinicRow } from "../../clinics/constant";
import type { UserRow } from "../types/type";

export const userRows: UserRow[] = [
  {
    id: 1,
    userId: "U001",
    username: "John Doe",
    roleType: "Admin",
    role: "Super Admin",
    email: "john.doe@example.com",
    contactNumber: "9876543210",
    status: "Active",
    action: "Edit",
  },
  {
    id: 2,
    userId: "U002",
    username: "Sarah Smith",
    roleType: "Manager",
    role: "Clinic Manager",
    email: "sarah.smith@example.com",
    contactNumber: "9876532109",
    status: "Inactive",
    action: "Edit",
  },
  {
    id: 3,
    userId: "U003",
    username: "Michael Brown",
    roleType: "Staff",
    role: "Nurse",
    email: "michael.brown@example.com",
    contactNumber: "9876512345",
    status: "Active",
    action: "Edit",
  },
  {
    id: 4,
    userId: "U004",
    username: "Emily Johnson",
    roleType: "Staff",
    role: "Technician",
    email: "emily.johnson@example.com",
    contactNumber: "9876587654",
    status: "Active",
    action: "Edit",
  },
  {
    id: 5,
    userId: "U005",
    username: "David Wilson",
    roleType: "Admin",
    role: "System Admin",
    email: "david.wilson@example.com",
    contactNumber: "9876578901",
    status: "Inactive",
    action: "Edit",
  },
];

// Example data
export const allClinicRows: ClinicRow[] = [
  {
    id: 1,
    clinicName: "Sunrise Clinic",
    speciality: "Cardiology",
    email: "contact@sunrise.com",
    address: "123 Main St, City",
    contactNumber: "+1 555 1234",
    status: "active",
  },
  {
    id: 2,
    clinicName: "Green Health",
    speciality: "General Practice",
    email: "hello@greenhealth.com",
    address: "456 Park Ave, City",
    contactNumber: "+1 555 5678",
    status: "inactive",
  },
];


export const locationRows = [
  {
    id: 1,
    locationName: "New York Clinic",
    phoneNumber: "9876543210",
    email: "ny-clinic@example.com",
    npiNumber: "1234567890",
    taxNumber: "TAX-98765",
    address: "123 Main Street, New York, NY 10001",
    status: "Active",
    action: "View",
  },
  {
    id: 2,
    locationName: "Los Angeles Clinic",
    phoneNumber: "9876541200",
    email: "la-clinic@example.com",
    npiNumber: "0987654321",
    taxNumber: "TAX-11223",
    address: "45 Sunset Blvd, Los Angeles, CA 90001",
    status: "Inactive",
    action: "View",
  },
  {
    id: 3,
    locationName: "Houston Clinic",
    phoneNumber: "9001122334",
    email: "houston-clinic@example.com",
    npiNumber: "5556667777",
    taxNumber: "TAX-33445",
    address: "88 Bay Area Road, Houston, TX 77001",
    status: "Pending",
    action: "View",
  },
  {
    id: 4,
    locationName: "Chicago Clinic",
    phoneNumber: "9022334455",
    email: "chicago-clinic@example.com",
    npiNumber: "6677889900",
    taxNumber: "TAX-88990",
    address: "25 Downtown St, Chicago, IL 60007",
    status: "Active",
    action: "View",
  },
  {
    id: 5,
    locationName: "Phoenix Clinic",
    phoneNumber: "9112233445",
    email: "phoenix-clinic@example.com",
    npiNumber: "1231231234",
    taxNumber: "TAX-55667",
    address: "66 Pine Street, Phoenix, AZ 85001",
    status: "Suspended",
    action: "View",
  },
];

// care team home page data
  export const peopleList = [
    { id: 1, name: "Dr. John Smith", role: "Primary Doctor", count: 11 },
    { id: 2, name: "Dr. Emily Carter", role: "Cardiologist", count: 21 },
    { id: 3, name: "Nurse Alex Brown", role: "Nurse", count: 67 },
  ];

  export const assignedClinics = [
    { id: 1, clinicName: "Sunrise Health Clinic", personId: 1, count: 31 },
    { id: 2, clinicName: "City Hospital", personId: 2, count: 24 },
    { id: 3, clinicName: "Metro Care Center", personId: 3, count: 2 },
    { id: 4, clinicName: "Green Valley Clinic", personId: 1, count: 24 },
  ];

  export const patientsData = [
    {
      id: 1,
      clinicId: 1,
      patientId: "P-1010",
      patientName: "John Doe",
      primaryProvider: "Dr. John Smith",
      dateOfBirth: "1985-04-20",
      lastReview: "2025-01-12",
      gmi: 6.8,
      timeInRange: 72,
      status: "Active",
    },
    {
      id: 2,
      clinicId: 1,
      patientId: "P-1011",
      patientName: "Amy Wilson",
      primaryProvider: "Dr. John Smith",
      dateOfBirth: "1988-09-14",
      lastReview: "2025-01-10",
      gmi: 7.2,
      timeInRange: 67,
      status: "Pending",
    },
    {
      id: 3,
      clinicId: 2,
      patientId: "P-1020",
      patientName: "Robert Davis",
      primaryProvider: "Dr. Emily Carter",
      dateOfBirth: "1976-03-09",
      lastReview: "2025-01-08",
      gmi: 7.5,
      timeInRange: 62,
      status: "Active",
    },
    {
      id: 4,
      clinicId: 3,
      patientId: "P-1030",
      patientName: "Sophia Martinez",
      primaryProvider: "Nurse Alex Brown",
      dateOfBirth: "1992-11-22",
      lastReview: "2025-01-07",
      gmi: 6.5,
      timeInRange: 81,
      status: "Inactive",
    },
    {
      id: 5,
      clinicId: 4,
      patientId: "P-1040",
      patientName: "Daniel Lee",
      primaryProvider: "Dr. John Smith",
      dateOfBirth: "1980-02-10",
      lastReview: "2025-01-05",
      gmi: 7.0,
      timeInRange: 70,
      status: "Active",
    },
  ];

