import type { ClinicRow } from "../../clinics/constant";
import type { PatientTaskRow, TaskRow } from "../../Tasks/constant";
import type { UserRow } from "../types/type";

export const userRows: UserRow[] = [
  {
    id: 1,
    userId: "U001",
    username: "John Doe",
    roleType: "Admin",
    role: "Super Admin",
    email: "john.doe@example.com",
    contactNumber: "9876543210",
    status: "Active",
    action: "Edit",
  },
  {
    id: 2,
    userId: "U002",
    username: "Sarah Smith",
    roleType: "Manager",
    role: "Clinic Manager",
    email: "sarah.smith@example.com",
    contactNumber: "9876532109",
    status: "Inactive",
    action: "Edit",
  },
  {
    id: 3,
    userId: "U003",
    username: "Michael Brown",
    roleType: "Staff",
    role: "Nurse",
    email: "michael.brown@example.com",
    contactNumber: "9876512345",
    status: "Active",
    action: "Edit",
  },
  {
    id: 4,
    userId: "U004",
    username: "Emily Johnson",
    roleType: "Staff",
    role: "Technician",
    email: "emily.johnson@example.com",
    contactNumber: "9876587654",
    status: "Active",
    action: "Edit",
  },
  {
    id: 5,
    userId: "U005",
    username: "David Wilson",
    roleType: "Admin",
    role: "System Admin",
    email: "david.wilson@example.com",
    contactNumber: "9876578901",
    status: "Inactive",
    action: "Edit",
  },
];

// Example data
export const allClinicRows: ClinicRow[] = [
  {
    id: 1,
    clinicName: "Sunrise Clinic",
    speciality: "Cardiology",
    email: "contact@sunrise.com",
    address: "123 Main St, City",
    contactNumber: "+1 555 1234",
    status: "active",
  },
  {
    id: 2,
    clinicName: "Green Health",
    speciality: "General Practice",
    email: "hello@greenhealth.com",
    address: "456 Park Ave, City",
    contactNumber: "+1 555 5678",
    status: "inactive",
  },
];

export const locationRows = [
  {
    id: 1,
    locationName: "New York Clinic",
    phoneNumber: "9876543210",
    email: "ny-clinic@example.com",
    npiNumber: "1234567890",
    taxNumber: "TAX-98765",
    address: "123 Main Street, New York, NY 10001",
    status: "Active",
    action: "View",
  },
  {
    id: 2,
    locationName: "Los Angeles Clinic",
    phoneNumber: "9876541200",
    email: "la-clinic@example.com",
    npiNumber: "0987654321",
    taxNumber: "TAX-11223",
    address: "45 Sunset Blvd, Los Angeles, CA 90001",
    status: "Inactive",
    action: "View",
  },
  {
    id: 3,
    locationName: "Houston Clinic",
    phoneNumber: "9001122334",
    email: "houston-clinic@example.com",
    npiNumber: "5556667777",
    taxNumber: "TAX-33445",
    address: "88 Bay Area Road, Houston, TX 77001",
    status: "Pending",
    action: "View",
  },
  {
    id: 4,
    locationName: "Chicago Clinic",
    phoneNumber: "9022334455",
    email: "chicago-clinic@example.com",
    npiNumber: "6677889900",
    taxNumber: "TAX-88990",
    address: "25 Downtown St, Chicago, IL 60007",
    status: "Active",
    action: "View",
  },
  {
    id: 5,
    locationName: "Phoenix Clinic",
    phoneNumber: "9112233445",
    email: "phoenix-clinic@example.com",
    npiNumber: "1231231234",
    taxNumber: "TAX-55667",
    address: "66 Pine Street, Phoenix, AZ 85001",
    status: "Suspended",
    action: "View",
  },
];

// care team home page data
export const peopleList = [
  { id: 1, name: "Dr. John Smith", role: "Primary Doctor", count: 11 },
  { id: 2, name: "Dr. Emily Carter", role: "Cardiologist", count: 21 },
  { id: 3, name: "Nurse Alex Brown", role: "Nurse", count: 67 },
];

export const assignedClinics = [
  { id: 1, clinicName: "Sunrise Health Clinic", personId: 1, count: 31 },
  { id: 2, clinicName: "City Hospital", personId: 2, count: 24 },
  { id: 3, clinicName: "Metro Care Center", personId: 3, count: 2 },
  { id: 4, clinicName: "Green Valley Clinic", personId: 1, count: 24 },
];

export const patientsData = [
  {
    id: 1,
    clinicId: 1,
    patientId: "P-1010",
    patientName: "John Doe",
    primaryProvider: "Dr. John Smith",
    dateOfBirth: "1985-04-20",
    lastReview: "2025-01-12",
    gmi: 6.8,
    timeInRange: 72,
    status: "Active",
  },
  {
    id: 2,
    clinicId: 1,
    patientId: "P-1011",
    patientName: "Amy Wilson",
    primaryProvider: "Dr. John Smith",
    dateOfBirth: "1988-09-14",
    lastReview: "2025-01-10",
    gmi: 7.2,
    timeInRange: 67,
    status: "Pending",
  },
  {
    id: 3,
    clinicId: 2,
    patientId: "P-1020",
    patientName: "Robert Davis",
    primaryProvider: "Dr. Emily Carter",
    dateOfBirth: "1976-03-09",
    lastReview: "2025-01-08",
    gmi: 7.5,
    timeInRange: 62,
    status: "Active",
  },
  {
    id: 4,
    clinicId: 3,
    patientId: "P-1030",
    patientName: "Sophia Martinez",
    primaryProvider: "Nurse Alex Brown",
    dateOfBirth: "1992-11-22",
    lastReview: "2025-01-07",
    gmi: 6.5,
    timeInRange: 81,
    status: "Inactive",
  },
  {
    id: 5,
    clinicId: 4,
    patientId: "P-1040",
    patientName: "Daniel Lee",
    primaryProvider: "Dr. John Smith",
    dateOfBirth: "1980-02-10",
    lastReview: "2025-01-05",
    gmi: 7.0,
    timeInRange: 70,
    status: "Active",
  },
];

export const allClinic = [
  {
    id: "CL001",
    name: "Sunrise Health Clinic",
    address: "123 Main Street, New York",
    phone: "212-555-1234",
  },
  {
    id: "CL002",
    name: "Green Valley Medical Center",
    address: "45 Greenway Road, California",
    phone: "310-555-7788",
  },
  {
    id: "CL003",
    name: "CityCare Family Clinic",
    address: "89 River Street, Texas",
    phone: "469-555-9123",
  },
  {
    id: "CL004",
    name: "Wellness Primary Care",
    address: "72 Hilltop Avenue, Florida",
    phone: "305-555-6451",
  },
  {
    id: "CL005",
    name: "Lakeside Medical Group",
    address: "250 Lakeshore Drive, Chicago",
    phone: "773-555-2204",
  },
];

export const allPatients = [
  { key: "P001", value: "John Doe" },
  { key: "P002", value: "Sarah Smith" },
  { key: "P003", value: "Michael Johnson" },
  { key: "P004", value: "Emily Brown" },
  { key: "P005", value: "David Wilson" },
];

export const groupRows = [
  {
    id: 1,
    groupName: "John Doe",
    GroupMember: "Administrator",
  },
  {
    id: 2,
    groupName: "Sarah Smith",
    GroupMember: "Doctor",
  },
  {
    id: 3,
    groupName: "Michael Johnson",
    GroupMember: "Nurse",
  },
  {
    id: 4,
    groupName: "Lisa Anderson",
    GroupMember: "Receptionist",
  },
  {
    id: 5,
    groupName: "David Wilson",
    GroupMember: "Billing Manager",
  },
];

export const groupRow = [
  {
    id: 1,
    groupName: "Admin Group",
    GroupMember: "John Doe, Alex Martin",
  },
  {
    id: 2,
    groupName: "Billing Group",
    GroupMember: "Sarah Smith, Tina Brown",
  },
  {
    id: 3,
    groupName: "Nurse Team",
    GroupMember: "Michael Johnson, Emily Davis",
  },
  {
    id: 4,
    groupName: "Doctor Group",
    GroupMember: "Dr. Robert Clark, Dr. Lisa Turner",
  },
  {
    id: 5,
    groupName: "Support Team",
    GroupMember: "Kevin Lee, Olivia Johnson",
  },
  {
    id: 6,
    groupName: "Reception Group",
    GroupMember: "Emma Wilson, Noah Patel",
  },
  {
    id: 7,
    groupName: "Pharmacy Team",
    GroupMember: "Harper Collins, Liam Walker",
  },
  {
    id: 8,
    groupName: "Lab Technicians",
    GroupMember: "Sophia Perez, Ethan Parker",
  },
  {
    id: 9,
    groupName: "IT Support",
    GroupMember: "Aiden Brooks, Mason Rivera",
  },
  {
    id: 10,
    groupName: "HR Department",
    GroupMember: "Ava Mitchell, Chloe Rogers",
  },
];

export const patientRows = [
  {
    id: 1,
    patientId: "P001",
    patientName: "John Doe",
    referringProvider: "Dr. Emily Carter",
    clinicName: "Sunrise Health Clinic",
    dateOfBirth: "1987-05-12",
    contactNumber: "+1 555-123-4567",
    email: "john.doe@example.com",
  },
  {
    id: 2,
    patientId: "P002",
    patientName: "Sarah Williams",
    referringProvider: "Dr. Robert Lee",
    clinicName: "Northside Medical Center",
    dateOfBirth: "1990-11-22",
    contactNumber: "+1 555-234-5678",
    email: "sarah.williams@example.com",
  },
  {
    id: 3,
    patientId: "P003",
    patientName: "Michael Johnson",
    referringProvider: "Dr. Hannah Kim",
    clinicName: "Green Valley Clinic",
    dateOfBirth: "1985-03-18",
    contactNumber: "+1 555-345-6789",
    email: "michael.johnson@example.com",
  },
  {
    id: 4,
    patientId: "P004",
    patientName: "Emily Davis",
    referringProvider: "Dr. Steven Clark",
    clinicName: "CarePoint Family Clinic",
    dateOfBirth: "1992-09-30",
    contactNumber: "+1 555-456-7890",
    email: "emily.davis@example.com",
  },
  {
    id: 5,
    patientId: "P005",
    patientName: "David Wilson",
    referringProvider: "Dr. Laura Perez",
    clinicName: "Wellness Medical Group",
    dateOfBirth: "1981-07-14",
    contactNumber: "+1 555-567-8901",
    email: "david.wilson@example.com",
  },

  {
    id: 6,
    patientId: "P006",
    patientName: "Olivia Brown",
    referringProvider: "Dr. Anthony Scott",
    clinicName: "HealthWay Clinic",
    dateOfBirth: "1994-02-10",
    contactNumber: "+1 555-678-9012",
    email: "olivia.brown@example.com",
  },
  {
    id: 7,
    patientId: "P007",
    patientName: "Ethan Miller",
    referringProvider: "Dr. Grace Cooper",
    clinicName: "Riverbend Medical Center",
    dateOfBirth: "1989-08-25",
    contactNumber: "+1 555-789-0123",
    email: "ethan.miller@example.com",
  },
  {
    id: 8,
    patientId: "P008",
    patientName: "Sophia Anderson",
    referringProvider: "Dr. Charles Morgan",
    clinicName: "Metro Healthcare",
    dateOfBirth: "1993-01-05",
    contactNumber: "+1 555-890-1234",
    email: "sophia.anderson@example.com",
  },
  {
    id: 9,
    patientId: "P009",
    patientName: "Liam Martinez",
    referringProvider: "Dr. Isabella Thomas",
    clinicName: "Premier Family Clinic",
    dateOfBirth: "1986-04-27",
    contactNumber: "+1 555-901-2345",
    email: "liam.martinez@example.com",
  },
  {
    id: 10,
    patientId: "P010",
    patientName: "Ava Thompson",
    referringProvider: "Dr. Benjamin Harris",
    clinicName: "Valley View Medical",
    dateOfBirth: "1991-10-16",
    contactNumber: "+1 555-012-3456",
    email: "ava.thompson@example.com",
  },
  {
    id: 11,
    patientId: "P011",
    patientName: "Noah Patel",
    referringProvider: "Dr. Benjamin Harris",
    clinicName: "Valley View Medical",
    dateOfBirth: "1991-10-17",
    contactNumber: "+1 555-012-3457",
    email: "noah.patel@example.com",
  },
];

export const taskData: TaskRow[] = [
  {
    id: "1",
    taskTitle: "Review Lab Report",
    category: "Lab",
    patientName: "John Doe",
    assignedBy: "Dr. Smith",
    assignedTo: "Nurse Kelly",
    createdOn: "2025-02-10",
    dueDate: "2025-02-15",
    source: "System",
    status: "todo",
    priority: "High",
  },
  {
    id: "2",
    taskTitle: "Schedule Follow-up Appointment",
    category: "Appointment",
    patientName: "Emma Watson",
    assignedBy: "Dr. Brown",
    assignedTo: "Reception",
    createdOn: "2025-02-09",
    dueDate: "2025-02-12",
    source: "Manual",
    status: "over-due",
    priority: "Low",
  },
  {
    id: "3",
    taskTitle: "Upload Insurance Documents",
    category: "Insurance",
    patientName: "Michael Johnson",
    assignedBy: "Admin",
    assignedTo: "Patient Support",
    createdOn: "2025-02-08",
    dueDate: "2025-02-20",
    source: "System",
    status: "todo",
    priority: "Low",
  },
  {
    id: "4",
    taskTitle: "Verify Patient Address",
    category: "Verification",
    patientName: "Sarah Lee",
    assignedBy: "Admin",
    assignedTo: "Support",
    createdOn: "2025-02-07",
    dueDate: "2025-02-14",
    source: "Manual",
    status: "completed",
    priority: "High",
  },
  {
    id: "5",
    taskTitle: "Prepare Discharge Summary",
    category: "Documentation",
    patientName: "David Clark",
    assignedBy: "Dr. Adams",
    assignedTo: "Nurse Helen",
    createdOn: "2025-02-05",
    dueDate: "2025-02-11",
    source: "System",
    status: "todo",
    priority: "High",
  },
  {
    id: "6",
    taskTitle: "Send Medication Reminder",
    category: "Reminder",
    patientName: "Olivia Brown",
    assignedBy: "System",
    assignedTo: "Nurse Team",
    createdOn: "2025-02-01",
    dueDate: "2025-02-10",
    source: "System",
    status: "completed",
    priority: "Low",
  },
  {
    id: "7",
    taskTitle: "Update Emergency Contact",
    category: "Profile Update",
    patientName: "Chris Evans",
    assignedBy: "Patient",
    assignedTo: "Support Team",
    createdOn: "2025-02-03",
    dueDate: "2025-02-08",
    source: "Manual",
    status: "over-due",
    priority: "High",
  },
  {
    id: "8",
    taskTitle: "Check MRI Availability",
    category: "Diagnostic",
    patientName: "Ava Thompson",
    assignedBy: "Dr. Carter",
    assignedTo: "Receptionist",
    createdOn: "2025-02-04",
    dueDate: "2025-02-18",
    source: "Manual",
    status: "todo",
    priority: "High",
  },
  {
    id: "9",
    taskTitle: "Update Allergy Information",
    category: "Medical Info",
    patientName: "Henry Wilson",
    assignedBy: "Patient",
    assignedTo: "Medical Staff",
    createdOn: "2025-02-02",
    dueDate: "2025-02-09",
    source: "System",
    status: "completed",
    priority: "Low",
  },
  {
    id: "10",
    taskTitle: "Fill Prescription Form",
    category: "Medication",
    patientName: "Sophia Garcia",
    assignedBy: "Dr. Green",
    assignedTo: "Pharmacy",
    createdOn: "2025-02-06",
    dueDate: "2025-02-13",
    source: "Manual",
    status: "todo",
    priority: "Low",
  },
];

export const patientTaskRows: PatientTaskRow[] = [
  {
    id: 1,
    taskName: "Check Vitals",
    Priority: "High",
    reviewedBy: "John Doe",
    dueDate: "2025-02-15",
    taskStatus: "To Do",
    taskType: "Through Alert",
    completedDate: "2025-02-15",
  },
  {
    id: 2,
    taskName: "Review Lab Report",
    Priority: "Medium",
    reviewedBy: "John Doe",
    dueDate: "2025-02-15",
    taskStatus: "Done",
    taskType: "Through Alert",
    completedDate: "2025-02-15",
  },
  {
    id: 3,
    taskName: "Review Lab Report",
    Priority: "Routing",
    reviewedBy: "John Doe",
    dueDate: "2025-02-15",
    taskStatus: "over due",
    taskType: "Through Alert",
    completedDate: "2025-02-15",
  },

  {
    id: 4,
    taskName: "Upload Medical Records",
    Priority: "Routing",
    reviewedBy: "Sarah Williams",
    dueDate: "2025-03-01",
    taskStatus: "done",
    taskType: "Manual Entry",
    completedDate: "",
  },
  {
    id: 5,
    taskName: "Schedule Follow-up Call",
    Priority: "High",
    reviewedBy: "John Doe",
    dueDate: "2025-02-20",
    taskStatus: "To Do",
    taskType: "Through Alert",
    completedDate: "",
  },
  {
    id: 6,
    taskName: "Medication Refill Approval",
    Priority: "Medium",
    reviewedBy: "Dr. Smith",
    dueDate: "2025-02-18",
    taskStatus: "Done",
    taskType: "Routing",
    completedDate: "2025-02-18",
  },
  {
    id: 7,
    taskName: "Patient Consent Verification",
    Priority: "High",
    reviewedBy: "Sarah Williams",
    dueDate: "2025-02-22",
    taskStatus: "over due",
    taskType: "Manual Entry",
    completedDate: "",
  },
  {
    id: 8,
    taskName: "Check Blood Sugar Report",
    Priority: "Medium",
    reviewedBy: "John Doe",
    dueDate: "2025-03-05",
    taskStatus: "to do",
    taskType: "Through Alert",
    completedDate: "",
  },
  {
    id: 9,
    taskName: "Insurance Verification",
    Priority: "Routing",
    reviewedBy: "Dr. Smith",
    dueDate: "2025-02-25",
    taskStatus: "Done",
    taskType: "Manual Entry",
    completedDate: "2025-02-24",
  },
  {
    id: 10,
    taskName: "Check Height & Weight",
    Priority: "Routing",
    reviewedBy: "Sarah Williams",
    dueDate: "2025-03-10",
    taskStatus: "To Do",
    taskType: "Through Alert",
    completedDate: "",
  },
  {
    id: 11,
    taskName: "Upload Scan Reports",
    Priority: "High",
    reviewedBy: "John Doe",
    dueDate: "2025-02-28",
    taskStatus: "over due",
    taskType: "Routing",
    completedDate: "",
  },
  {
    id: 12,
    taskName: "Monitor BP Readings",
    Priority: "Medium",
    reviewedBy: "Dr. Smith",
    dueDate: "2025-03-12",
    taskStatus: "to do",
    taskType: "Manual Entry",
    completedDate: "",
  },
  {
    id: 13,
    taskName: "Update Medical History",
    Priority: "Routing",
    reviewedBy: "Sarah Williams",
    dueDate: "2025-03-01",
    taskStatus: "Done",
    taskType: "Through Alert",
    completedDate: "2025-03-01",
  },
  {
    id: 14,
    taskName: "Check Pulse Rate",
    Priority: "Medium",
    reviewedBy: "John Doe",
    dueDate: "2025-03-15",
    taskStatus: "To Do",
    taskType: "Routing",
    completedDate: "",
  },
  {
    id: 15,
    taskName: "Patient Identity Verification",
    Priority: "High",
    reviewedBy: "Sarah Williams",
    dueDate: "2025-02-21",
    taskStatus: "over due",
    taskType: "Manual Entry",
    completedDate: "",
  },
  {
    id: 16,
    taskName: "Confirm Appointment",
    Priority: "Routing",
    reviewedBy: "Dr. Smith",
    dueDate: "2025-03-08",
    taskStatus: "Done",
    taskType: "Through Alert",
    completedDate: "2025-03-07",
  },
  {
    id: 17,
    taskName: "Analyze ECG Report",
    Priority: "High",
    reviewedBy: "John Doe",
    dueDate: "2025-03-03",
    taskStatus: "over due",
    taskType: "Routing",
    completedDate: "",
  },
  {
    id: 18,
    taskName: "Collect Patient Feedback",
    Priority: "Routing",
    reviewedBy: "Sarah Williams",
    dueDate: "2025-03-20",
    taskStatus: "To Do",
    taskType: "Manual Entry",
    completedDate: "",
  },
  {
    id: 19,
    taskName: "Review Medication Changes",
    Priority: "Medium",
    reviewedBy: "Dr. Smith",
    dueDate: "2025-03-02",
    taskStatus: "Done",
    taskType: "Through Alert",
    completedDate: "2025-03-02",
  },
  {
    id: 20,
    taskName: "Check Oxygen Saturation",
    Priority: "High",
    reviewedBy: "John Doe",
    dueDate: "2025-02-27",
    taskStatus: "over due",
    taskType: "Through Alert",
    completedDate: "",
  },
  {
    id: 21,
    taskName: "Verify Insurance Approval",
    Priority: "Routing",
    reviewedBy: "Sarah Williams",
    dueDate: "2025-03-11",
    taskStatus: "done",
    taskType: "Manual Entry",
    completedDate: "",
  },
  {
    id: 22,
    taskName: "Upload Updated Prescription",
    Priority: "Medium",
    reviewedBy: "Dr. Smith",
    dueDate: "2025-03-14",
    taskStatus: "To Do",
    taskType: "Through Alert",
    completedDate: "",
  },
  {
    id: 23,
    taskName: "Update Emergency Contact",
    Priority: "Routing",
    reviewedBy: "John Doe",
    dueDate: "2025-03-18",
    taskStatus: "Done",
    taskType: "Routing",
    completedDate: "2025-03-18",
  },
];
